### ISSUE TITLE
Credo agent failing to start

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#888]
In the most recent test runs, the Credo agent is failing to start, resulting in all tests failing.

**Comment by nodlesh** [comment]
I believe that the Credo agent is actually starting, however it is taking longer to start in some instances than the 30 second timer we have set waiting to get a status. This is manifesting now because we no longer run tests if we don't get a status on an agent. In the past it would carry on and we wouldn't notice.  I think we need to extend the checking of status to 60 seconds. 
I've seen this a couple times with ACAPy as well.

**Comment by nodlesh** [comment]
I may be mistaken and the credo agent is actually not starting. I am getting a Require ESM error when building locally now. A bad library version update maybe.

**Comment by swcurran** [comment]
Any luck resolving this?  When I run it locally, no logs are written, so I can't see anything to debug.  AFAIK, the build works fine.

**Comment by nodlesh** [comment]
Not yet. I'm working through the package.json trying to pin modules to previous versions but not luck. 

This is the error.
```
Starting Credo agent ...
yarn run v1.22.22
$ /src/node_modules/.bin/ts-node src/index.ts -p 9030 -i false
/src/node_modules/@tsed/common/lib/cjs/exports.js:5
require("@tsed/logger");
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /src/node_modules/@tsed/logger/lib/esm/index.js from /src/node_modules/@tsed/common/lib/cjs/exports.js not supported.
Instead change the require of index.js in /src/node_modules/@tsed/common/lib/cjs/exports.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/src/node_modules/@tsed/common/lib/cjs/exports.js:5:1) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
So something has changed in Tsed/common or logger.

**Comment by nodlesh** [comment]
After working with the main Ts.ED maintainers, they have fixed a v6 peer dependancy and a v7 peer dependancy. This has fixed our immediate problem. However, I am still working with them to move the credo backchannel to Ts.ED v7 permanently so this will be less likely to happen again. So if we can get to a working v7 I will still do a PR for that. I'll only spend a few more hours on that and if we can't sort it will revert to v6 as is. 
Closing this issue since credo tests behaved normally in last night's run.

**Comment by swcurran** [comment]
Awesome stuff — well done!!
